package com.feedz.feedz;
// Generated May 5, 2018 5:41:17 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Feed generated by hbm2java
 */
public class Feed  implements java.io.Serializable {


     private Integer id;
     private String title;
     private String url;
     private String description;
     private String image;
     private Date created;
     private Date updated;
     private Set feedUsers = new HashSet(0);

    public Feed() {
    }

    public Feed(String title, String url, String description, String image, Date created, Date updated, Set feedUsers) {
       this.title = title;
       this.url = url;
       this.description = description;
       this.image = image;
       this.created = created;
       this.updated = updated;
       this.feedUsers = feedUsers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public Set getFeedUsers() {
        return this.feedUsers;
    }
    
    public void setFeedUsers(Set feedUsers) {
        this.feedUsers = feedUsers;
    }




}


