package com.feedz.models;
// Generated May 5, 2018 5:41:17 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * FeedItem generated by hbm2java
 */
public class FeedItem  implements java.io.Serializable {


     private Integer id;
     private String title;
     private String link;
     private String description;
     private String comments;
     private String author;
     private String category;
     private Integer mediaItemId;
     private Date created;
     private Date updated;

    public FeedItem() {
    }

    public FeedItem(String title, String link, String description, String comments, String author, String category, Integer mediaItemId, Date created, Date updated) {
       this.title = title;
       this.link = link;
       this.description = description;
       this.comments = comments;
       this.author = author;
       this.category = category;
       this.mediaItemId = mediaItemId;
       this.created = created;
       this.updated = updated;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public Integer getMediaItemId() {
        return this.mediaItemId;
    }
    
    public void setMediaItemId(Integer mediaItemId) {
        this.mediaItemId = mediaItemId;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }




}


