package com.feedz.models;
// Generated May 5, 2018 5:41:17 PM by Hibernate Tools 4.3.1



/**
 * FeedUser generated by hbm2java
 */
public class FeedUser  implements java.io.Serializable {


     private Integer id;
     private Feed feed;
     private User user;

    public FeedUser() {
    }

    public FeedUser(Feed feed, User user) {
       this.feed = feed;
       this.user = user;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Feed getFeed() {
        return this.feed;
    }
    
    public void setFeed(Feed feed) {
        this.feed = feed;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


