package com.feedz.models;
// Generated May 5, 2018 5:41:17 PM by Hibernate Tools 4.3.1



/**
 * MediaItem generated by hbm2java
 */
public class MediaItem  implements java.io.Serializable {


     private Integer id;
     private String url;
     private String type;

    public MediaItem() {
    }

    public MediaItem(String url, String type) {
       this.url = url;
       this.type = type;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


