package com.feedz.models;
// Generated May 5, 2018 5:41:17 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private String email;
     private String password;
     private boolean hasNotifications;
     private Date created;
     private Date updated;
     private Set feedUsers = new HashSet(0);

    public User() {
    }

	
    public User(boolean hasNotifications) {
        this.hasNotifications = hasNotifications;
    }
    public User(String firstName, String lastName, String email, String password, boolean hasNotifications, Date created, Date updated, Set feedUsers) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.password = password;
       this.hasNotifications = hasNotifications;
       this.created = created;
       this.updated = updated;
       this.feedUsers = feedUsers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isHasNotifications() {
        return this.hasNotifications;
    }
    
    public void setHasNotifications(boolean hasNotifications) {
        this.hasNotifications = hasNotifications;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public Set getFeedUsers() {
        return this.feedUsers;
    }
    
    public void setFeedUsers(Set feedUsers) {
        this.feedUsers = feedUsers;
    }




}


